# Boolean and Comparison Operations

In [1]:
!pip install numpy --upgrade

In [2]:
import numpy as np

### all
- Check if all elements satisfy a condition
- **Syntax**: `numpy.all(a, axis=None, out=None, keepdims=<no value>, *, where=<no value>)`

In [3]:
np.all([[True,False],[True,True]])

np.False_

In [4]:
np.all([[True,False],[True,True]], axis=0)

array([ True, False])

In [5]:
np.all([[True, True], [False, True]], where=[[True], [False]])

np.True_

In [8]:
o=np.array(False)
z=np.all([-1, 4, 5], out=o)
id(z), id(o), z , o # may vary

(139771735143696, 139771735143696, array(True), array(True))

### any
- Check if any element satisfies a condition
- **Syntax**: `numpy.any(a, axis=None, out=None, keepdims=<no value>, *, where=<no value>)`

In [9]:
np.any([[True, False], [True, True]])

np.True_

In [11]:
np.any([[True,  False, True ],
        [False, False, False]], axis=0)

array([ True, False,  True])

In [13]:
a = np.array([[1, 0, 0],
              [0, 0, 1],
              [0, 0, 0]])
np.any(a, axis=0), np.any(a, axis=1)

(array([ True, False,  True]), array([ True,  True, False]))

### isfinite
- Check for finite values
- **Syntax**: `numpy.isfinite(x, /, out=None, *, where=True)`
- Not a Number, positive infinity and negative infinity are considered to be non-finite

In [16]:
np.isfinite(1)

np.True_

In [15]:
np.isfinite(0)

np.True_

In [17]:
np.isfinite(np.nan)

np.False_

In [18]:
np.isfinite(np.inf),np.isfinite(-np.inf)

(np.False_, np.False_)

In [20]:
x = np.array([-np.inf, 0., np.inf])
y = np.array([2, 2, 2])
np.isfinite(x, y)

array([0, 1, 0])

In [21]:
y

array([0, 1, 0])

### ifinf
- Check for infinite values
- **Syntax**: `numpy.isinf(x, /, out=None, *, where=True)`

In [24]:
np.isinf(np.inf), np.isinf(-np.inf)

(np.True_, np.True_)

In [25]:
np.isinf(np.nan)

np.False_

In [30]:
np.isinf(57),np.isinf(1+9j)

(np.False_, np.False_)

In [26]:
x = np.array([-np.inf, 0., np.inf])
y = np.array([2, 2, 2])
np.isinf(x, y)

array([1, 0, 1])

In [27]:
y

array([1, 0, 1])

### isnan
- Check for NaNs
- **Syntax**: `numpy.isnan(x, /, out=None, *, where=True)`

In [31]:
np.isnan(np.nan)

np.True_

In [32]:
np.isnan(np.inf)

np.False_

### Reference
-  [numpy: Logic Function](https://numpy.org/doc/stable/reference/routines.logic.html)