# Creating and Initializing Arrays

In [6]:
!pip install numpy --upgrade

In [ ]:
import numpy as np

### **np.array()**

- Create arrays
- **Syntax**: `numpy.array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0, like=None)`
    - object - list or nested-list that will be converted to array like [ [ 1 , 2 ] , [ 3 , 4 ] ]
    - dtype - desired data-type for the array (defualt = int64 or int32)
    - copy - If True (default), then the array data is copied
    - order - Specify the memory layout of the array (see [docs](https://numpy.org/doc/stable/reference/generated/numpy.array.html) for more info)
    - subok - If True, then sub-classes will be passed-through, otherwise the returned array will be forced to be a base-class array (default).
    - ndim - Specifies the minimum number of dimensions that the resulting array should have
    - like - Reference object to allow the creation of arrays which are not NumPy arrays.


In [5]:
np.array([1,2,3])

array([1, 2, 3])

In [8]:
np.array([1, 2, 3.0])

array([1., 2., 3.])

In [9]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [11]:
np.array([1, 2, 3], ndmin=3)

array([[[1, 2, 3]]])

In [12]:
np.array([1,2,3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [13]:
np.array(np.asmatrix('1 2; 3 4'), subok=True)

matrix([[1, 2],
        [3, 4]])

### **numpy.zeros()**
- Return a new array of given shape and type, filled with zeros.
- **Syntax**: `numpy.zeros(shape, dtype=float, order='C', *, like=None)`



In [17]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
np.zeros((5,), dtype=int)

array([0, 0, 0, 0, 0])

In [20]:
np.zeros([2,2,3])

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [21]:
np.zeros((2,), dtype=[('x', 'i4'), ('y', 'i4')]) # custom dtype

array([(0, 0), (0, 0)], dtype=[('x', '<i4'), ('y', '<i4')])

### **numpy.zeros_like()**
- Return an array of zeros with the same shape and type as a given array.
- **Syntax**: `numpy.zeros_like(a, dtype=None, order='K', subok=True, shape=None, *, device=None)`
  - device: The device on which to place the created array. (cpu or gpu)


In [32]:
x = [[1,2,3],[2,5,6]]
np.zeros_like(x)

array([[0, 0, 0],
       [0, 0, 0]])

In [33]:
x = np.arange(16).reshape((4, 4))
np.zeros_like(x)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

### **numpy.ones()**
- same as zeros() but with 1
- **Syntax**: `numpy.ones(shape, dtype=None, order='C', *, device=None, like=None)`

In [34]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [35]:
np.ones((5), dtype=int)

array([1, 1, 1, 1, 1])

In [36]:
np.ones([4,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### **numpy.ones_like()**
- Same as zeros_like but with 1
- **Syntax**: `numpy.ones_like(a, dtype=None, order='K', subok=True, shape=None, *, device=None`

In [37]:
x = [[1,2,3],[2,5,6]]
np.ones_like(x)

array([[1, 1, 1],
       [1, 1, 1]])

In [38]:
x = np.arange(16).reshape((4, 4))
np.ones_like(x)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

### **numpy.full()**
- Return a new array of given shape and type, filled with *fill_value*.
- **Syntax**: `numpy.full(shape, fill_value, dtype=None, order='C', *, device=None, like=None)`

In [39]:
np.full((2, 2), np.inf)

array([[inf, inf],
       [inf, inf]])

In [40]:
np.full((4,4),[1,2,3,4])

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

### **numpy.empty()**
- Return a new array of given shape and type, without initializing entries.
- **Syntax**: `numpy.empty(shape, dtype=float, order='C', *, device=None, like=None)`

In [41]:
np.empty([2, 2]) # uninitialized

array([[4.9e-324, 9.9e-324],
       [1.5e-323, 2.0e-323]])

In [43]:
np.empty([2, 2], dtype=int) # uninitialized

array([[1, 2],
       [3, 4]])

### **numpy.empty_like()**
- Return a new array with the same shape and type as a given array.
- **Syntax**: `numpy.empty_like(prototype, dtype=None, order='K', subok=True, shape=None, *, device=None)`


In [45]:
a = ([1,2,3], [4,5,6])
np.empty_like(a) # uninitialized


array([[      102683177,               0, 140550553073456],
       [       10798352, 140549106399984, 140550553073840]])

In [46]:
a = [[1.1,2.2,3.3],[4.4,5.5,6.6]]
np.empty_like(a) # uninitialized

array([[2.91070381e-316, 0.00000000e+000, 5.19201334e-316],
       [6.94412048e-310, 5.09145399e-316, 6.94404863e-310]])

### **numpy.eye()**
- Return a 2-D array with ones on the diagonal and zeros elsewhere.
- **Syntax**: `numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, device=None, like=None)`
  - N - Number of rows in the output.
  - M - Number of columns in the output. If None, defaults to N.
  - k - Index of the diagonal: 0 (the default) refers to the main diagonal, a positive value refers to an upper diagonal, and a negative value to a lower diagonal.


In [47]:
np.eye(2, dtype=int)

array([[1, 0],
       [0, 1]])

In [52]:
np.eye(3, k=1), np.eye(3, k=0)

(array([[0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 0.]]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

### **numpy.identity()**
- Return the identity array.The identity array is a square array with ones on the main diagonal.
- **Syntax**: `numpy.identity(n, dtype=None, *, like=None)`

In [53]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### **numpy.arange()**
- Return evenly spaced values within a given interval.
- **Syntax**: `numpy.arange([start, ]stop, [step, ]dtype=None, *, device=None, like=None)`

In [54]:
np.arange(4)

array([0, 1, 2, 3])

In [57]:
np.arange(3,7)

array([3, 4, 5, 6])

In [58]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

### **numpy.linspace()**
- Return evenly spaced numbers over a specified interval.
- **Syntax**: `numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0, *, device=None)`

In [59]:
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [60]:
np.linspace(2.0, 3.0, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [61]:
np.linspace(2.0, 3.0, num=5, retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

- Use `np.arange()` when you care about step size.
- Use `np.linspace()` when you care about the number of points.
- `np.linspace()` is better for floating-point numbers because it's more precise.
- Which one should you use?
  - If you want fixed spacing, go with `arange()`.
  - If you want a specific number of points, go with `linspace()`.

### **np.random.rand()**
- Random values in a given shape.
- **Syntax**: `random.rand(d0, d1, ..., dn)`


In [64]:
np.random.rand(3,2) # Random samples from uniform distribution (0,1)

array([[0.74081427, 0.8902915 ],
       [0.06520686, 0.05130925],
       [0.91891829, 0.75443934]])

### **np.random.randn()**
- Random samples from normal distribution
- **Syntax**: `numpy.random.randn(d0, d1, ..., dn)`

In [65]:
np.random.randn()

0.290879005383138

In [67]:
10 + 2 * np.random.randn(2, 4) # Two-by-four array of samples from the normal distribution with mean 3 and standard deviation 2.5

array([[ 9.33516862,  7.40641078,  8.42549359, 11.8776971 ],
       [11.5933156 , 10.92857404,  9.18557111, 11.19032411]])

For random samples from the normal distribution with mean *mu* and standard deviation *sigma*, use:

`sigma * np.random.randn(...) + mu`

### **np.random.randint()**
- Random integers in a given range
- **Syntax**: `numpy.random.randint(low, high=None, size=None, dtype=int)`

In [71]:
np.random.randint(2, size=10)

array([0, 0, 1, 0, 0, 0, 1, 0, 1, 1])

In [68]:
np.random.randint(2, 20, size=10)

array([ 4, 18, 10,  2, 10,  5,  4,  7, 12, 16])

In [70]:
np.random.randint(0,4, size=(2,4))

array([[1, 0, 0, 3],
       [1, 1, 1, 3]])

In [72]:
np.random.randint(1,[3,5,7]) # a 1 x 3 array with 3 different upper bounds

array([2, 4, 4])

In [73]:
np.random.randint([1,2,3],5)# a 1 by 3 array with 3 different lower bounds

array([1, 3, 3])

In [76]:
np.random.randint([1, 3, 5, 7], [[10], [20]], dtype=np.uint8)
# a 2 by 4 array using broadcasting with dtype of uint8
# numpy generates this code like this

# np.random.randint([[1, 3, 5, 7],
#                   [1, 3, 5, 7]],
#                  [[10, 10, 10, 10],
#                   [20, 20, 20, 20]], dtype=np.uint8)
#
# So NumPy will generate a (2,4) array where:
# Row 1 → Random numbers between [1-10], [3-10], [5-10], [7-10].
# Row 2 → Random numbers between [1-20], [3-20], [5-20], [7-20].


array([[ 6,  6,  9,  9],
       [ 3,  4, 18, 11]], dtype=uint8)

### Reference
- [numpy](https://numpy.org/doc/stable/user/index.html#user)