# Indexing and Slicing

In [1]:
!pip install numpy --upgrade

In [2]:
import numpy as np

### where
- Return elements chosen from x or y depending on condition.
- Conditional indexing (e.g., np.where(arr > 0, 1, 0)
- **Syntax**: `numpy.where(condition, [x, y, ]/)`

In [5]:
a = np.arange(10)
np.where(a < 5)

(array([0, 1, 2, 3, 4]),)

In [9]:
np.where(a < 5, a, a*10) , np.where(a > 5, a, a*10)

(array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90]),
 array([ 0, 10, 20, 30, 40, 50,  6,  7,  8,  9]))

In [11]:
np.where([[True, False], [True, True]],
         [[1, 2], [3, 4]],
         [[9, 8], [7, 6]])
# It checks each element in condition.
# If True, it picks the corresponding element from x.
# If False, it picks the corresponding element from y.
# [[ True  False]
# [ True   True]]
# x - >
#   [[1  2]
#   [3  4]]
#
# y ->
#   [[9  8]
#   [7  6]]
#
#   |:---------:|:-----------:|:-----------:|:------------:|
#   | Condition | Pick from x | Pick from y | Final Result |
#   |:---------:|:-----------:|:-----------:|:------------:|
#   |   True	|      1	  |      -	    |      1       |
#   |   False	|      -	  |      8	    |      8       |
#   |   True	|      3	  |      -	    |      3       |
#   |   True	|      4	  |      -	    |      4       |
#   |:---------:|:-----------:|:-----------:|:------------:|

array([[1, 8],
       [3, 4]])

In [14]:
a = np.array([[0, 1, 2],
              [0, 2, 4],
              [0, 3, 6]])
np.where(a < 4, a, -1)

array([[ 0,  1,  2],
       [ 0,  2, -1],
       [ 0,  3, -1]])

### Take
- Select elements at specific indices
- **Syntax**: `numpy.take(a, indices, axis=None, out=None, mode='raise')`
  - mode - Specifies how out-of-bounds indices will behave.
    - 'raise' - raise an error (default)
    - 'wrap' - wrap around
    - 'clip' - clip to the range
      - 'clip' mode means that all indices that are too large are replaced by the index that addresses the last element along that axis. Note that this disables indexing with negative numbers.

In [15]:
a = [4, 3, 5, 7, 6, 8]
indices = [0, 1, 4]
np.take(a, indices)

array([4, 3, 6])

In [18]:
np.take(a, [[0, 1], [2, 3]]) # If indices is not one dimensional, the output also has these dimensions.

array([[4, 3],
       [5, 7]])

### Argsort
- Returns the indices that would sort an array.
- **Syntax**: `numpy.argsort(a, axis=-1, kind=None, order=None, *, stable=None)`
  - kind - {‘quicksort’, ‘mergesort’, ‘heapsort’, ‘stable’}
  -

In [22]:
x = np.array([3, 1, 2])
np.argsort(x) # it returns array indexes of the elements
# [1 -> 1] [2 -> 2] [0 -> 3]

array([1, 2, 0])

In [32]:
x = np.array([[0, 3], [2, 2]])
np.argsort(x, axis=0)  # sorts along first axis (down)

array([[0, 1],
       [1, 0]])

In [31]:
np.argsort(x, axis=1)  # sorts along last axis (across)

array([[0, 1],
       [0, 1]])

### argmax
- Get index of max value
- **Syntax**: `numpy.argmax(a, axis=None, out=None, *, keepdims=<no value>)`

In [39]:
a = np.arange(6).reshape(2,3) + 10
a, np.argmax(a)

(array([[10, 11, 12],
        [13, 14, 15]]),
 np.int64(5))

In [37]:
np.argmax(a, axis=0)
# column 1 -> [10,13] -> max[index] = 1
# column 2 -> [11,14] -> max[index] = 1
# column 3 -> [12,15] -> max[index] = 1

array([1, 1, 1])

In [40]:
np.argmax(a, axis=1)
# row 1 -> [10,11,12] -> max[index] = 2
# row 1 -> [13,14,15] -> max[index] = 2

array([2, 2])

### argmin
- Get index of min value
- **Synatx**: `numpy.argmin(a, axis=None, out=None, *, keepdims=<no value>)`


In [43]:
a = np.arange(6).reshape(2,3) + 10
a, np.argmin(a)

(array([[10, 11, 12],
        [13, 14, 15]]),
 np.int64(0))

In [47]:
np.argmin(a, axis=0)
# column 1 -> [10,13] -> min[index] = 0
# column 2 -> [11,14] -> min[index] = 0
# column 3 -> [12,15] -> min[index] = 0

array([0, 0, 0])

In [49]:
np.argmin(a, axis=1)
# row 1 -> [10,11,12] -> min[index] = 0
# row 1 -> [13,14,15] -> min[index] = 0

array([0, 0])

### References
- [numpy: Sorting, searching, and counting](https://numpy.org/doc/stable/reference/routines.sort.html)