# Linear Algebra


In [1]:
!pip install numpy --upgrade

In [2]:
import numpy as np

#### dot()
 - **Syntax**: `numpy.dot(a, b, out=None)`

In [3]:
a = np.array([1,2,3])
b = np.array([2,3,4])
np.dot(a,b) # Returns the dot product of a and b. If a and b are both scalars or both 1-D arrays then a scalar is returned; otherwise an array is returned.
# (1*2) + (2*3) + (3*4)
#If both a and b are 1-D arrays, it is inner product of vectors.
#If both a and b are 2-D arrays, it is matrix multiplication, but using matmul or a @ b is preferred.

np.int64(20)

In [4]:
np.dot(2,4)

np.int64(8)

In [5]:
a = np.array([1+2j,3+4j])
b = np.array([4+3j,2+1j])
np.dot(a,b) # j is just i for python (imaginary number)

np.complex128(22j)

In [6]:
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
np.dot(a, b)

array([[4, 1],
       [2, 2]])

#### **vdot()**
 - Return the dot product of two vectors.
 - **Syntax**:` numpy.vdot(a, b)`

In [7]:
a = np.array([1+2j,3+4j])
b = np.array([4+3j,2+1j])
np.vdot(a,b) #i took this code from above dot() example. Look at that output, why both are different? answered below

# For complex vectors a and b, dot product is:
# dot(a,b) = Σ (aᵢ × bᵢ)
# result_dot = np.dot(a,b)
# = (1+2j)(4+3j) + (3+4j)(2+1j)

# vdot takes the complex conjugate of the first vector:
# vdot(a,b) = Σ (aᵢ* × bᵢ) where aᵢ* is complex conjugate
# result_vdot = np.vdot(a,b)
# = (1-2j)(4+3j) + (3-4j)(2+1j)

np.complex128(20-10j)

For dot:

 - First term: (1+2j)(4+3j) = 4 + 3j + 8j + 6j² = 4 + 11j - 6 = -2 + 11j
 - Second term: (3+4j)(2+1j) = 6 + 3j + 8j + 4j² = 6 + 11j - 4 = 2 + 11j
 - Sum: (-2 + 11j) + (2 + 11j) = 22j

For vdot:

 - First term: (1-2j)(4+3j) = 4 - 8j + 3j - 6j² = 4 - 5j + 6 = 10 - 5j
 - Second term: (3-4j)(2+1j) = 6 - 8j + 3j - 4j² = 6 - 5j + 4 = 10 - 5j
 - Sum: (10 - 5j) + (10 - 5j) = 20 - 10j

In [8]:
a = np.array([[10,20], [50, 60]])
b = np.array([[40, 30], [5, 10]])
np.vdot(a, b), np.vdot(b, a) #10*40 + 20*30 + 50*5 + 60*10

(np.int64(1850), np.int64(1850))

#### **vecdot()**
- Vector dot product of two arrays.
- Let be a vector in x1 and  be a corresponding vector in x2. The dot product is defined as:
    \begin{align}\mathbf{a} \cdot \mathbf{b} = \sum_{i=0}^{n-1} \overline{a}_i b_i\end{align}
- where the sum is over the last dimension (unless axis is specified) and where  denotes the complex conjugate if  is complex and the identity otherwise.

In [11]:
a = np.array([[1,1,0],[1,0,1],[0,1,1]])
b = np.array([10,20,30])
np.vecdot(a,b) # [10*1 + 20*1 + 30*0, 10*1 + 20*0 + 30*1, 10*0+ 20*1 + 30*1]

array([30, 40, 50])

`numpy.linalg.vecdot()` is also have same usage

In [13]:
np.linalg.vecdot(a,b)

array([30, 40, 50])

#### **tensordot() // linlalg.tensordot()**
- It computes the dot product along specified axes of two multi-dimensional arrays (tensors).
- **Syntax**: `numpy.tensordot(a, b, axes=n)`

Think of it like this:
- If dot() is for 1D vectors,
- And matmul() is for 2D matrices,
- Then tensordot() is for higher-dimensional tensors, letting you choose which dimensions to contract.


In [20]:
import numpy as np

A = np.array([[1, 2], [3, 4]])  # Shape (2,2)
B = np.array([[5, 6], [7, 8]])  # Shape (2,2)

result_0 = np.tensordot(A, B, axes=0)  # Contract along the last axis of A and first axis of B
result_1 = np.tensordot(A, B, axes=1)  # Contract along the last axis of A and first axis of B # Equivalent to A @ B (matrix multiplication).
print(f"Axis=0->\n{result_0}\nAxis=1->\n{result_1}")

Axis=0->
[[[[ 5  6]
   [ 7  8]]

  [[10 12]
   [14 16]]]


 [[[15 18]
   [21 24]]

  [[20 24]
   [28 32]]]]
Axis=1->
[[19 22]
 [43 50]]


In [22]:
A = np.random.rand(2, 3, 4)  # Shape (2,3,4)
B = np.random.rand(4, 3, 2)  # Shape (4,3,2)

result = np.tensordot(A, B, axes=([1, 2], [1, 0]))  # Contract axes (1,2) of A with (1,0) of B
print(result.shape)  # (2,2)

(2, 2)


- tensordot() is like an advanced dot product for higher-dimensional tensors.
- You control which axes to multiply over.
- When axes=1, it behaves like matrix multiplication.
- When axes=([x, y], [p, q]), it generalizes to multi-axis contraction.

**numpy.linalg.svd()**
- numpy.linalg.svd() stands for **Singular Value Decomposition** (SVD).
- It factorizes a matrix into three matrices:
    \begin{align}\mathbf{A} = \mathbf{U} \cdot \mathbf{S} \cdot \mathbf{V}^{T}  \end{align}
    - A → Original matrix (shape:m * n)
    - U → Left singular vectors (shape: m * m)
    - S → Singular values (1D array of size min(m, n))
    - Vᵀ → Right singular vectors (shape: n * n)

For Better Understanding Read This : https://www.geeksforgeeks.org/singular-value-decomposition-svd/


In [31]:
A = np.array([[1, 2], [3, 4], [5, 6]])  # Shape (3,2)

U, S, Vt = np.linalg.svd(A)

print("U:\n", U)   # Left singular vectors (3x3)
print("S:\n", S)   # Singular values (2,)
print("Vt:\n", Vt) # Right singular vectors (2x2)
#S contains singular values, which indicate the "importance" of each dimension.

U:
 [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
S:
 [9.52551809 0.51430058]
Vt:
 [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


In [40]:
# Reconstructing the original matrix
# Since S is returned as a 1D array, we must convert it to a diagonal matrix before reconstructing:
m, n = A.shape
S_mat = np.zeros((m, n))
S_mat[:n, :n] = np.diag(S)

S_mat[1,1] = 0 # Try printing A_reconstructed with this line. You will notice with this line we dont get exact value but without this line we get our original matrix A.
# In S, we have two elements, as we already know S tell us the importance of each dimension of a matrix,since, our S is -> [9.52551809 0.51430058]. From line 3-5 we
# made our S into 2D array from 1D-array. and we diagonalised it because Matrix multiplication needs correct shapes → U (m×m), S (m×n), Vt (n×n).
# but what happened in line 7? We just removed least important values from S_mat (try printing S_mat before setting S_mat[1,1] to 0 and after setting it equal).
# by this we lost some data while preserving the main structure. So, what is the use of this?


A_reconstructed = U @ S_mat @ Vt  # Matrix multiplication
print("Reconstructed A:\n", A_reconstructed)

Reconstructed A:
 [[1.35662819 1.71846235]
 [3.09719707 3.92326845]
 [4.83776596 6.12807454]]


**How does this work?**
 - We compute the SVD of matrix A → U, S, Vt
 - We create a full diagonal matrix from S
 - We set the smallest singular value to zero, removing the least significant component
 - We reconstruct A using the modified S

**What happens?**
 - The compressed matrix will be very close to A but with some lost detail.
 - If A was an image, setting small values to zero would reduce noise while preserving the main structure.
 - If A was data, this process could be used for dimensionality reduction (like in PCA).

**Why is this useful?**
- Image Compression → Less storage, still visually similar.
- Data Compression → Lower memory, faster computation.
- Noise Reduction → Removing minor variations that don’t matter.
- Dimensionality Reduction → Keep the most important info while discarding unimportant details.


In [50]:
# Create a 3x3 matrix
A = np.array([[4, 2, 0],
              [9, 6, 3],
              [2, 7, 5]])

# Compute SVD
U, S, Vt = np.linalg.svd(A)

# Convert S (1D array) to diagonal matrix
S_matrix = np.zeros((A.shape[0], A.shape[1]))
np.fill_diagonal(S_matrix, S)

# Zero out the smallest singular value (low-rank approximation)
S_matrix[2, 2] = 0  # Removing the least important component
# S_matrix[1,1] = 0 # try running with this and see how much of data we lost
# Reconstruct the compressed matrix
A_compressed = U @ S_matrix @ Vt

print("Original Matrix:\n", A)
print("Compressed Matrix:\n", np.round(A_compressed, 2))


Original Matrix:
 [[4 2 0]
 [9 6 3]
 [2 7 5]]
Compressed Matrix:
 [[4.09 1.69 0.38]
 [8.95 6.15 2.81]
 [2.02 6.94 5.08]]


#### **numpy.linalg.eig()**

- Compute the eigenvalues and right eigenvectors of a square array.

- **Syntax**: `numpy.linalg.eig(a)`


In [52]:
eigenvalues, eigenvectors = np.linalg.eig(np.diag((1, 2, 3)))
eigenvalues, eigenvectors

(array([1., 2., 3.]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

In [54]:
eigenvalues, eigenvectors = np.linalg.eig(np.array([[1, -1], [1, 1]]))
eigenvalues, eigenvectors

(array([1.+1.j, 1.-1.j]),
 array([[0.70710678+0.j        , 0.70710678-0.j        ],
        [0.        -0.70710678j, 0.        +0.70710678j]]))

In [57]:
a = np.array([[1, 2j], [-2j, 1]])
eigenvalues, eigenvectors = np.linalg.eig(a)
eigenvalues, eigenvectors

(array([ 3.+0.j, -1.+0.j]),
 array([[ 0.70710678+0.j        , -0.        -0.70710678j],
        [-0.        -0.70710678j,  0.70710678+0.j        ]]))

#### **numpy.linalg.det()**
- Compute the determinant of a matrix
- **Syntax**: `numpy.linalg.det(a)`

In [58]:
a = np.array([[1,2],[3,4]])
det = np.linalg.det(a)
det # may vary

np.float64(-2.0000000000000004)

In [59]:
a = np.array([ [[1, 2], [3, 4]], [[1, 2], [2, 1]], [[1, 3], [3, 1]] ])
det = np.linalg.det(a)
det

array([-2., -3., -8.])

**slogdet** - Another way to represent the determinant, more suitable for large matrices where underflow/overflow may occur.



#### **numpy.trace() // numpy.linalg.trace()**
- Return the sum along diagonals of the array.
- **Syntax**: `numpy.trace(a, offset=0, axis1=0, axis2=1, dtype=None, out=None)`


  - a - Input array, from which diagonals are tekn
  - offset - it's like adding or subtracting a number from all elements from that diagonal
  - axes - If a has more than two dimensions, then the axes specified by axis1 and axis2 are used
  - dtype - Determines the data-type of the returned array
  - out - to save the output into something (it must be of the right shape to hold the output)

In [61]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.trace(a)

np.int64(15)

In [60]:
a = np.arange(8).reshape(2,2,2)
np.trace(a)

array([6, 8])

In [63]:
a = np.arange(24).reshape((2,2,2,3))
np.linalg.trace(a).shape

(2, 2)

#### **numpy.linalg.inv()**

- Compute the inverse of a matrix.
- **Syntax**: `numpy.linalg.inv(a)`

Key points about matrix inverses:
- **Square matrix requirement**: Only square matrices can have inverses.
- **Non-singular condition**: A matrix is considered "non-singular" if its determinant is not zero, which is necessary for an inverse to exist.
- **Identity matrix product**: The product of a matrix and its inverse always equals the identity matrix (I).

If a is detected to be singular, a LinAlgError is raised. If a is ill-conditioned, a LinAlgError may or may not be raised, and results may be inaccurate due to floating-point errors.

In [64]:
a = np.array([[1,2],[3,4]])
a_inv = np.linalg.inv(a)
a_inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [68]:
np.allclose(a @ a_inv, np.eye(2)) # checks if matrix multiplication of our a and inverse of a is equal to identity matrix with similar shape or not

True

In [69]:
# If a matrix is close to singular, the computed inverse may not satisfy a @ ainv = ainv @ a = eye(a.shape[0]) even if a LinAlgError is not raised:
a = np.array([[2,4,6],[2,0,2],[6,8,14]])
np.linalg.inv(a)

array([[-1.12589991e+15, -5.62949953e+14,  5.62949953e+14],
       [-1.12589991e+15, -5.62949953e+14,  5.62949953e+14],
       [ 1.12589991e+15,  5.62949953e+14, -5.62949953e+14]])

In [72]:
a @ np.linalg.inv(a) # may vary

array([[ 0.  ,  0.  ,  0.  ],
       [-0.5 ,  0.75,  0.25],
       [ 0.  ,  0.  ,  1.  ]])

To detect ill-conditioned matrices, you can use numpy.linalg.cond to compute its [condition number](https://www.cse.iitd.ac.in/~dheerajb/CS210_lect07.pdf). The larger the condition number, the more ill-conditioned the matrix is. As a rule of thumb, if the condition number cond(a) = 10**k, then you may lose up to k digits of accuracy on top of what would be lost to the numerical method due to loss of precision from arithmetic methods.

In [73]:
np.linalg.cond(a)

np.float64(8.659885634118668e+17)

In [74]:
# It is also possible to detect ill-conditioning by inspecting the matrix’s singular values directly.
# The ratio between the largest and the smallest singular value is the condition number:
sigma = np.linalg.svd(a, compute_uv=False)  # Do not compute singular vectors
sigma.max()/sigma.min() # may vary

np.float64(8.659885634118668e+17)

#### References
- [numpy.linalg](https://numpy.org/doc/stable/reference/routines.linalg.html)