# Mathematical Operations

### Prerequisites
If you dont know basic trignometry , logarithmic or exponential functions/operations, I would suggest you to learn them first.
- [Exponents and Logarithms](https://www.mathsisfun.com/algebra/exponents-logarithms.html)
- [Trignometry](https://www.mathsisfun.com/algebra/trigonometry.html)

In [1]:
!pip install numpy --upgrade

In [2]:
import numpy as np

### Power
- Element-wise exponentiation
- **Syntax**:  `numpy.power(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature]) = <ufunc 'power'>`

In [3]:
x1 = np.array([1,2,3])
np.power(x1, 2)

array([1, 4, 9])

In [5]:
x2 = [1.0, 2.0, 3.0]
np.power(x1, x2)

array([ 1.,  4., 27.])

In [6]:
a = np.array([1,2,3,4,5,6])
b = np.array([[1, 2, 3, 3, 2, 1], [1, 2, 3, 3, 2, 1]])
np.power(a,b)

array([[ 1,  4, 27, 64, 25,  6],
       [ 1,  4, 27, 64, 25,  6]])

Negative values raised to a non-integral value will result in `nan`

### exp
- Exponential function $e^{x}$
- **Syntax**: `numpy.exp(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature]) = <ufunc 'exp'>`

- The irrational number e is also known as Euler’s number. It is approximately 2.718281, and is the base of the natural logarithm, ln

In [8]:
np.exp(4)

np.float64(54.598150033144236)

In [12]:
x = np.linspace(-2*np.pi, 2*np.pi, 10)
np.exp(x)

array([1.86744273e-03, 7.54460979e-03, 3.04807938e-02, 1.23144711e-01,
       4.97513941e-01, 2.00999393e+00, 8.12052740e+00, 3.28075445e+01,
       1.32544960e+02, 5.35491656e+02])

### log
- Natural logarithm
- **Syntax**: `numpy.log(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature]) = <ufunc 'log'>`
- The natural logarithm log is the inverse of the exponential function, so that log(exp(x)) = x. The natural logarithm is logarithm in base e.



In [15]:
x = np.array([1,2,3,4,5])
np.log(x)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

### log10
- Base-10 logarithm
- **Syntax**: `numpy.log10(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature]) = <ufunc 'log10'>`

In [20]:
np.log10([1,20,3,100])

array([0.        , 1.30103   , 0.47712125, 2.        ])

### sqrt
- Square root
- **Syntax**: `numpy.sqrt(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature]) = <ufunc 'sqrt'>`

In [21]:
np.sqrt([1,4,9])

array([1., 2., 3.])

In [22]:
np.sqrt([4, -1, np.inf])

<ipython-input-22-b744eda02914>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt([4, -1, np.inf])


array([ 2., nan, inf])

In [23]:
np.sqrt([4, -1, -3+4J])

array([2.+0.j, 0.+1.j, 1.+2.j])

## Trigonometric functions

### sin
- **Syntax**: `numpy.sin(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature]) = <ufunc 'sin'>`

In [25]:
np.sin(np.pi/2)

np.float64(1.0)

In [28]:
np.sin(np.array((0., 30., 45., 60., 90.)) * np.pi / 180. )

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

### cos
- **Syntax**: `numpy.cos(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature]) = <ufunc 'cos'>`

In [31]:
np.cos(np.array([0, np.pi/2, np.pi]))

array([ 1.000000e+00,  6.123234e-17, -1.000000e+00])

### tan
- **Syntax**: `numpy.tan(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature]) = <ufunc 'tan'>`

In [30]:
np.tan(np.array([-np.pi,np.pi/2,np.pi]))

array([ 1.22464680e-16,  1.63312394e+16, -1.22464680e-16])