# Introduction to Numpy

In [1]:
import numpy as np

# VECTORS

A vector is essentially an ordered list of numbers. Each number in the list is called an element or component of the vector. Vectors are fundamental data structures used to represent numerical data.

In [6]:
vector_row = np.array([1, 2, 3])
print("Row Vector: ",vector_row)

vector_column = np.array([[1], [2], [3]])
print("Column Vector: \n",vector_column)

Row Vector:  [1 2 3]
Column Vector: 
 [[1]
 [2]
 [3]]


# MATRIX

- A matrix in computer science is like a table of numbers or symbols. Think of it as a grid with rows and columns, where each cell in the grid holds a piece of information. These pieces of information are called elements.
- In mathematics, a matrix is a rectangular array of numbers, symbols, or expressions, arranged in rows and columns
- Rows tun horizontally and columns run vertically

#### Create a Matrix
 - **Syntax**: `np.matrix(data)`

In [7]:
mat1 = np.matrix("1, 2, 3, 4; 4, 5, 6, 7; 7, 8, 9, 10")
print(mat1)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]


In [8]:
mat2 = np.array([[1, 2], [3,4], [4, 6]])
print(mat2)

[[1 2]
 [3 4]
 [4 6]]


#### Shape of a matrix
- **Syntax**: `mat.shape`
    -  **`shape[0]`** - returns the number of rows
    - **`shape[1]`** - returns the number of columns

In [15]:
# shape
mat1.shape, mat2.shape
#shape[0] is row and shape[1] is column
print(f"{mat1}\nrow = {mat1.shape[0]}\nColumn = {mat1.shape[1]}")

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]
row = 3
Column = 4


#### Size
- **Syntax**: `array.size`

In [16]:
#size
mat1.size #-> number of elements (rows *  columns)

12

#### Modifying Matrix Using Insert
- **Syntax:** `np.insert(matrix, object, values, axis)`
  - **matrix** - input matrix
  - **object** - index position
  - **values** - matrix of values to be inserted


In [40]:
#insert -> array
a = np.array([1,2,3,4])
b = np.insert(a, 2, 5) # Insert 5 before index 2
print(b)

[1 2 5 3 4]


In [41]:
a = np.array([[1,2],[3,4]])
b = np.insert(a, 1, [5,6], axis=0) # Insert [5,6] before row index 1
print(b)

[[1 2]
 [5 6]
 [3 4]]


In [48]:
a = np.array([1,2,3,4])
b = np.insert(a, [1,3], [5,6]) # Insert 5 before index 1 and 6 before index 3
print(b)

[1 5 2 3 6 4]


In [47]:
a = np.array([1,2,3,4])
b = np.insert(a, slice(1,3),[5,6]) # Insert [5,6] before indices 1 (inclusive) to 3 (exclusive)
print(b) # The values in values ([5, 6]) are inserted before the elements within the specified slice (indices 1 and 2 in this case).

[1 5 2 6 3 4]


* **Specific Indices vs. Range**: In the first `case ([1, 3])`, you provide explicit indices for insertion. In the second case `(slice(1, 3))`, you define a range of indices.
* **Insertion Behavior**: With explicit indices, values are inserted at those precise locations. With a slice, values are inserted sequentially before the elements within the slice.

In [50]:
a = np.array([[1,2],[3,4]])
b = np.insert(a, 1, [5,6], axis=1) # Insert [5,6] before column index 1
print(b)

[[1 5 2]
 [3 6 4]]


In [42]:
#insert -> Matrix // 2D-array
col_new = np.matrix("1, 1, 1")
print(col_new)

mat4 = np.insert(mat1, 0, col_new, axis=1) #-> col_new is inserted in mat1 at index 0
# axis=0: Insert along rows (vertical)
# axis=1: Insert along columns (horizontal)
# axis=None: Flatten and insert in the flattened array
print(f"MAT1 ->\n{mat1}\nMAT4 ->\n{mat4}")

[[1 1 1]]
MAT1 ->
[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]
MAT4 ->
[[ 1  1  2  3  4]
 [ 1  4  5  6  7]
 [ 1  7  8  9 10]]


In [43]:
row_new = np.matrix("0, 0, 0, 0")
print(row_new)
mat5 = np.insert(mat1, 0, row_new, axis=0)
print(mat5)

[[0 0 0 0]]
[[ 0  0  0  0]
 [ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]


In [44]:
a = np.array([[1, 2], [3, 4]])  # 2x2 array
b = np.insert(a, 1, [5, 6], axis=1)  # Insert [5, 6] before column index 1
print(b)

[[1 5 2]
 [3 6 4]]


#### Modifying Matrix Using Index
- **Syntax**: `mat[row_index, col_index)`

In [54]:
mat_a = np.matrix("1, 2, 3, 4, 5; 5, 6, 7, 8, 9; 9, 10, 11, 12, 13")
print(mat_a)

[[ 1  2  3  4  5]
 [ 5  6  7  8  9]
 [ 9 10 11 12 13]]


In [56]:
mat_a[1,1] = 0 # row 1 and column 1 element (6) is changed to 0
print(mat_a)

[[ 1  2  3  4  5]
 [ 5  0  7  8  9]
 [ 9 10 11 12 13]]


In [65]:
mat_a[1,:] # extracted 2nd row (not index 2nd)
# mat_a[1:] prints matrix([[ 5,  0,  7,  8,  9],[ 9, 10, 11, 12, 13]])
# the comma "," tells python to only check the given row or column
# as we did in list indexing, without using it gives all elements from that index of row or column
# In simpler terms: Imagine you have a chocolate, now you want 2nd row i.e. index 1
# if we break it from before index 1 , we have two peices (i.e. we used it without a delimiter (,)) but we specificaly
# need the the second row (idk why), so break it again, now this time before row 3 (i.e we used a delimiter),
# now we have our second row.
# i dont think that is a good example.

matrix([[5, 0, 7, 8, 9]])

In [72]:
mat_a[:,2] # extracted 3rd column (index 2)
#mat_a[: 2]
# The `:` before the `2` means "select from the beginning up to (but not including) index 2"
#mat_a[:,2] is like highlighting the entire 3rd column of the spreadsheet.
# mat_a[: 2] is like highlighting the first 2 rows of the spreadsheet.

[[ 3]
 [ 7]
 [11]] [[1 2 3 4 5]
 [5 0 7 8 9]]


**Think of it this way**:
 - Imagine a grid with rows and columns. The comma in slicing helps you navigate and "zoom in" on specific parts of that grid. The part before the comma controls your vertical movement (rows), and the part after the comma controls your horizontal movement (columns).

**Why is it necessary?**
 - Matrices (and NumPy arrays in general) are multi-dimensional. To access or manipulate specific elements, rows, or columns, you need a way to tell Python which dimension you're working with. The comma provides that distinction.


**Without the comma**:
 - If you omit the comma, Python assumes you're working with a single dimension. For example, mat_a[1] would try to select the element at index 1 in the flattened (1-dimensional) version of the matrix, which might not be what you intended.

In essence, the comma is essential for navigating and slicing multi-dimensional data structures in Python, especially when working with matrices and NumPy arrays. It allows you to precisely select the data you need by specifying both row and column positions.

In [74]:
mat_a[1,2] # extracting a element

7

#### Matrix Operations

**arange()**: Creates an array of evenly spaced values within a given interval. It is similar to Python's built-in `range()` function but returns a NumPy array instead of a list.
 - **Syntax**: `numpy.arange([start, ]stop, [step, ], dtype=None)`

**reshape()**: As the name suggests, Reshaping means changing the shape of an array.(From 1-D to 2-D or vice-versa).
 - **Syntax**: `numpy.reshape(array, newshape)`

In [77]:
A = np.arange(0,20).reshape(5, 4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [78]:
B = np.arange(20, 40).reshape(5,4)
print(B)

[[20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]]


##### ADDITION

 - **np.add()**- performs element-wise addition between two matrices
 - **Syntax**: `np.add(matrix_1, matrix_2)`


In [79]:
np.add(A,B)

array([[20, 22, 24, 26],
       [28, 30, 32, 34],
       [36, 38, 40, 42],
       [44, 46, 48, 50],
       [52, 54, 56, 58]])

##### SUBTRACTION
 - np.subtract(): performs element-wise subtraction between two matrices.
 - **Syntax**: `np.subtract(matrix_1, matrix_2)`


In [80]:
np.subtract(A,B)

array([[-20, -20, -20, -20],
       [-20, -20, -20, -20],
       [-20, -20, -20, -20],
       [-20, -20, -20, -20],
       [-20, -20, -20, -20]])

##### TRANSPOSE
The transpose of a matrix is a new matrix created by switching the rows and columns of the original matrix. It's represented by the original matrix's name with a superscript "T". For example, the transpose of matrix "A" is "Aᵀ".

 - `np.transpose()` - Permute the dimensions of an array.
 - **Syntax**: `np.transpose(matrix)`


In [83]:
A = np.arange(0, 20).reshape(5,4)
print(A)
np.transpose(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

##### MULTIPLICATION
 - **np.dot()** - performs matrix multiplication between two matrices.
 - **Syntax**: `np.dot(matrix_1, matrix_2)`

In [93]:
# np.dot(A,B) # this will give error because when multiplying two matrices first matrix column should be equal to the row of second matrix
# shape of A is (5,4) and shape of B is also (5,4)
# we need to change either one of our matrix shape to (4,5)
np.dot(A,B.reshape(4,5)) # A.shape = (5,4) | B.shape = (4,5)

T = np.transpose(B)
np.dot(A,T)

array([[ 134,  158,  182,  206,  230],
       [ 478,  566,  654,  742,  830],
       [ 822,  974, 1126, 1278, 1430],
       [1166, 1382, 1598, 1814, 2030],
       [1510, 1790, 2070, 2350, 2630]])

In [96]:
#using matmul
np.matmul(A,T)

array([[ 134,  158,  182,  206,  230],
       [ 478,  566,  654,  742,  830],
       [ 822,  974, 1126, 1278, 1430],
       [1166, 1382, 1598, 1814, 2030],
       [1510, 1790, 2070, 2350, 2630]])

In [97]:
# using @ operator
A @ T

array([[ 134,  158,  182,  206,  230],
       [ 478,  566,  654,  742,  830],
       [ 822,  974, 1126, 1278, 1430],
       [1166, 1382, 1598, 1814, 2030],
       [1510, 1790, 2070, 2350, 2630]])

##### Element-wise multiplication¶
 - **np.multiply()** - performs element-wise multiplication between two matrices.
 - **Syntax**: `np.multiply(matrix1, matrix2)`


In [99]:
np.multiply(A,B) # this is not matrix multiplication. we are just doing addition but with multiplication.

array([[  0,  21,  44,  69],
       [ 96, 125, 156, 189],
       [224, 261, 300, 341],
       [384, 429, 476, 525],
       [576, 629, 684, 741]])

**Division**
 - **np.divide()** - performs element-wise division between two matrices.
 - **Syntax**: `np.divide(matrix_1, matrix_2)`

In [100]:
np.divide(A, B)

array([[0.        , 0.04761905, 0.09090909, 0.13043478],
       [0.16666667, 0.2       , 0.23076923, 0.25925926],
       [0.28571429, 0.31034483, 0.33333333, 0.35483871],
       [0.375     , 0.39393939, 0.41176471, 0.42857143],
       [0.44444444, 0.45945946, 0.47368421, 0.48717949]])

## References

*   [https://numpy.org/](https://numpy.org/)
*   [https://www.kaggle.com/code/jhossain/introduction-to-numpy-vectors-and-matrices](https://www.kaggle.com/code/jhossain/introduction-to-numpy-vectors-and-matrices)